services:
  web:
    image: toptuji/kupon4uk:latest
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "5433:5433"
    environment:
      - NODE_ENV=production
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./seo-data.json:/app/seo-data.json:rw
      - ./promo-data.json:/app/promo-data.json:rw
      - ./promo-state.json:/app/promo-state.json:rw
      - ./usage-data.json:/app/usage-data.json:rw
